modLoader = "javafml"
loaderVersion = "[44,)"
license = "Code: LGPLv3 \nAssets: All Rights Reserved"
issueTrackerURL = "https://github.com/AOCAWOL/BYG/issues"
[[mods]]
modId = "byg"
version="${file.jarVersion}"
displayName = "Oh The Biomes You'll Go"
displayURL = "https://oh-the-biomes-youll-go.fandom.com/wiki/Oh_The_Biomes_You%27ll_Go_Wiki"
logoFile = "logo_text.png"
credits = "Some Artwork: CupOfJoe, SaltySeaDoggo, Spare, Paul; Some Code: TelepathicGrunt, Paul, HauntedPasta, TheModdingInquisition, J.T. McQuigg(JT122406)"
authors = "AOCAWOL, Corgi Taco, YaBoiChips"
description = '''
An Adventure and Exploration mod with over 80 new biomes!

Notice: The linked wiki is not owned by BYG, the wiki is open for anyone to edit and any inaccuracies that may appear are not BYG's responsibility.
'''
[[dependencies.byg]]
modId = "forge"
mandatory = true
versionRange = "[44.1.00,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.byg]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.byg]]
modId = "terrablender"
mandatory = true
versionRange = "[2.1.0.132,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.byg]]
modId = "corgilib"
mandatory = true
versionRange = "[2.0.0.0,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.byg]]
modId = "geckolib"
mandatory = true
versionRange = "[4.0.6,)"
ordering = "BEFORE"
side = "BOTH"