
modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="https://github.com/CorgiTaco/BYG/issues"
[[mods]]
modId="byg"
version="1.0.11"
displayName="Oh The Biomes You'll Go"
displayURL="https://biomesyougo.weebly.com/"
logoFile="logo_text.png"
credits="AOCAWOL & FoundSporeYT, Translators: Dimiral(Russian), Godzmoline(Simplified Chinese)"
authors="AOCAWOL & FoundSporeYT"
description='''
An Adventure and Exploration mod with over 60 new biomes!
'''
[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
